import {useMemo,useState} from 'react'
import {api} from './lib/api'
import {saveThenExport} from './lib/exportWorkflow'
import {covers,deriveElements} from './lib/operationState'
import {commit,initialHistory,redo,undo,type History} from './lib/history'
import {PdfViewer} from './components/PdfViewer'
import type {BBox,DocumentInfo,Layout,Operation,Rotation,VisualElement} from './types'
import './styles.css'

const uid=()=>crypto.randomUUID()
type Tool='select'|'add'|'cover'
export default function App(){
 const [doc,setDoc]=useState<DocumentInfo>();const [layouts,setLayouts]=useState<Layout[]>([]);const [draft,setDraft]=useState<{id:string;revision:number}>();const [history,setHistory]=useState<History>(initialHistory);const [selectedId,setSelectedId]=useState<string>();const [text,setText]=useState('');const [fontSize,setFontSize]=useState(12);const [textColor,setTextColor]=useState('#17201b');const [coverColor,setCoverColor]=useState('#FFFFFF');const [tool,setTool]=useState<Tool>('select');const [busy,setBusy]=useState('');const [download,setDownload]=useState('');const [error,setError]=useState('')
 const ops=history.present;const visual=useMemo(()=>deriveElements(layouts,ops),[layouts,ops]);const selected=visual.find(e=>e.id===selectedId);const coverOverlays=useMemo(()=>covers(ops),[ops])
 async function upload(file:File){setBusy('正在读取结构');setError('');try{const d=await api.upload(file);setDoc(d);const all=await Promise.all(Array.from({length:d.page_count},(_,i)=>api.layout(d.document_id,i)));setLayouts(all);setDraft(await api.createDraft(d.document_id));setHistory(initialHistory);setSelectedId(undefined);setDownload('')}catch(e){setError(String(e))}finally{setBusy('')}}
 function add(op:Omit<Operation,'id'|'seq'>){setHistory(h=>commit(h,[...h.present,{...op,id:uid(),seq:h.present.length+1}]))}
 function select(e:VisualElement){setSelectedId(e.id);setText(e.text);setFontSize(e.style.font_size_pt);setTextColor(e.style.color);setTool('select')}
 async function save(){if(!draft)return;setBusy('保存草稿');setError('');try{const r=await api.save(draft.id,draft.revision,ops);setDraft({...draft,revision:r.revision})}catch(e){setError(String(e))}finally{setBusy('')}}
 async function exportPdf(){if(!draft)return;setBusy('保存当前编辑并生成新版本');setError('');try{const r=await saveThenExport(api,draft,ops);setDraft({...draft,revision:r.revision});setDownload(api.download(r.version_id))}catch(e){setError(String(e))}finally{setBusy('')}}
 function replace(){if(selected&&!selected.deleted&&selected.editability==='native')add({type:'replace_text',page_index:selected.page_index,target_element_id:selected.id,bbox:selected.bbox,payload:{text},style:{...selected.style,font_size_pt:fontSize,color:textColor}})}
 function moveElement(id:string,page:number,bbox:BBox){const item=visual.find(e=>e.id===id);if(item&&!item.deleted&&item.editability==='native')add({type:'move_text',page_index:page,target_element_id:id,bbox})}
 function region(page:number,bbox:BBox){if(tool==='add'){const id=`a:${uid()}`;add({type:'add_text',page_index:page,created_element_id:id,bbox,payload:{text:text||'新增文字'},style:{font_family:'helv',font_size_pt:fontSize,color:textColor,align:'left',rotation:0}});setSelectedId(id)}else if(tool==='cover')add({type:'cover_region',page_index:page,bbox,payload:{cover_color:coverColor}});setTool('select')}
 const disabled=!selected||selected.deleted||selected.editability!=='native'
 return <main>
  <header><div className="brand"><span className="mark">P/</span><div><b>Papertrail</b><small>LOCAL PDF WORKBENCH</small></div></div><div className="trust"><i/> 源文件永不修改</div><label className="upload">{doc?'更换 PDF':'选择 PDF'}<input type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></header>
  {!doc?<section className="empty"><p className="eyebrow">DETERMINISTIC · PRIVATE · LOCAL</p><h1>把改动留在<br/><em>操作轨迹</em>里。</h1><p>点击原生文字，修改、拖动或删除；也可以在任意页拖框覆盖并叠加新文字。无需云端 AI。</p><label className="drop">上传普通 PDF 开始<input type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><span>≤100 MB · ≤300 页</span></label></section>:
  <div className="workspace"><aside className="left"><p className="label">文档</p><h2>{doc.page_count} 页</h2><code>{doc.upload_sha256.slice(0,16)}…</code><div className="rail">{layouts.map(l=><a key={l.page_index} href={`#page-${l.page_index}`}>{String(l.page_index+1).padStart(2,'0')}<span>{l.elements.length} 个文本框</span></a>)}</div><div className="warnings"><b>编辑提示</b><p>任何内容编辑都会使现有数字签名失效。</p><p>扫描覆盖只是视觉覆盖，不是安全脱敏。</p></div></aside>
   <section className="viewer"><div className="toolbar"><button onClick={()=>setHistory(undo(history))} disabled={!history.past.length}>↶ 撤销</button><button onClick={()=>setHistory(redo(history))} disabled={!history.future.length}>↷ 重做</button><span>{ops.length} 个操作</span><button onClick={save}>保存草稿</button><button className="export" onClick={exportPdf}>保存并导出 PDF</button>{download&&<a className="download" href={download}>下载版本 ↓</a>}</div><PdfViewer url={api.file(doc.document_id)} layouts={layouts} elements={visual} covers={coverOverlays} selected={selectedId} tool={tool} onSelect={select} onRegion={region} onMove={moveElement}/></section>
   <aside className="inspector"><p className="label">检查器</p><div className="tool-tabs"><button className={tool==='select'?'active':''} onClick={()=>setTool('select')}>选择/拖动</button><button className={tool==='add'?'active':''} onClick={()=>setTool('add')}>新增文字</button><button className={tool==='cover'?'active':''} onClick={()=>setTool('cover')}>覆盖区域</button></div>{tool==='cover'?<><p className="muted">在任意页面拖框确认覆盖范围；单击会创建 170×32 pt 区域。预览会即时显示。</p><label>覆盖颜色<input type="color" value={coverColor} onChange={e=>setCoverColor(e.target.value.toUpperCase())}/></label></>:<><label>{tool==='add'?'新增文字内容':'文字内容'}<textarea value={text} onChange={e=>setText(e.target.value)}/></label><div className="style-row"><label>字号<input type="number" min="4" max="144" value={fontSize} onChange={e=>setFontSize(Number(e.target.value))}/></label><label>颜色<input type="color" value={textColor} onChange={e=>setTextColor(e.target.value)}/></label></div>{tool==='add'&&<p className="muted">现在到目标页点击或拖框放置文字。新增后可直接选中、拖动、替换或删除。</p>}</>}{selected&&<><hr/><span className="tag">{selected.kind==='added'?'新增元素':selected.editability==='native'?'原生文字':'仅覆盖'}</span><h3>{selected.text}</h3>{selected.deleted?<p className="deleted-note">此元素已删除。请撤销后再操作。</p>:selected.editability==='cover_only'?<p className="muted">复杂方向文字仅允许使用覆盖区域和新增文字，不能原生替换、移动或删除。</p>:<><button className="primary" disabled={disabled} onClick={replace}>应用替换</button><p className="muted">可在画布上直接拖动所选文字。</p><button className="danger" disabled={disabled} onClick={()=>add({type:'delete_text',page_index:selected.page_index,target_element_id:selected.id})}>删除文字</button></>}</>} {!selected&&tool==='select'&&<p className="muted">点击页面中的文字框开始编辑；原生或新增文字均可直接拖动。</p>}</aside>
  </div>}{busy&&<div className="toast">{busy}…</div>}{error&&<div className="error" onClick={()=>setError('')}>{error}</div>}
 </main>
}
